name: luckygo_admin
description: A new Flutter project with Google Maps on Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  geolocator: ^11.1.0
  firebase_core: 3.15.2
  cloud_firestore: 5.6.11

  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/luckygo_logo.png
    - assets/images/special2.png
    - assets/images/wheelchair.png
    - assets/images/blind_symbol.png
    - assets/images/deaf_symbol.png
    - assets/images/ind_supportstick.png
    - assets/images/mute_symbol.png
    - assets/images/stroller.png
    - assets/images/ind_stroller.png
    - assets/images/shopping_1.png
    - assets/images/shopping_2.png
    - assets/images/shopping_3.png
    - assets/images/shopping_4.png
    - assets/images/shopping_5.png
    - assets/images/luggage_1.png
    - assets/images/luggage_2.png
    - assets/images/luggage_3.png
    - assets/images/luggage_4.png
    - assets/images/luggage_5.png
    - assets/images/ind_adult.png
    - assets/images/ind_baby.png
    - assets/images/ind_wheelchair.png
    - assets/images/ind_shopping1.png
    - assets/images/ind_shopping2.png
    - assets/images/ind_shopping3.png
    - assets/images/ind_shopping4.png
    - assets/images/ind_shopping5.png
    - assets/images/ind_luggage1.png
    - assets/images/ind_luggage2.png
    - assets/images/ind_luggage3.png
    - assets/images/ind_luggage4.png
    - assets/images/ind_luggage5.png
    - assets/images/ind_pets.png
    - assets/images/ind_dog.png
    - assets/images/ind_goat.png
    - assets/images/ind_rooster.png
    - assets/images/ind_snake.png
    - assets/images/ind_durian.png
    - assets/images/ind_odourfruits.png
    - assets/images/ind_wetfood.png
    - assets/images/ind_tupperware.png
    - assets/images/ind_gastank.png
    - assets/images/presenter.png
    - assets/images/ind_passenger.png
    - assets/images/destination_marker.png
    - assets/images/earth.png
    - assets/images/aim_1.png
    - assets/images/d1.png
    - assets/images/d2.png
    - assets/images/d3.png
    - assets/images/d4.png
    - assets/images/d5.png
    - assets/images/rhb_logo.png
    - assets/images/maybank_logo.png
    - assets/images/public_bank_logo.png
    - assets/images/cimb_bank_logo.png
    - assets/images/hong_leong_bank_logo.png
    - assets/images/alliance_bank_logo.png
    - assets/images/bsn_logo.png





